package main

import (
	"log"
	"os"
	"path/filepath"
	"strings"
	"time"
)

type Config struct {
	// Paths are resolved relative to the config file's parent directory, unless absolute.
	ContentDir   string `json:"content_dir"`
	RawInputsDir string `json:"raw_inputs_dir"`
	PromptsDir   string `json:"prompts_dir"`
	StateFile    string `json:"state_file"`

	AudioRecorderDir string `json:"audio_recorder_dir"`

	AppleHealthExportDir string `json:"apple_health_export_dir"`

	SecretsFile string `json:"secrets_file"`

	// HealthFile is the path (relative to content_dir) where health metrics are
	// written before each new session. Default: "AutoGenerated/health.md".
	HealthFile string `json:"health_file"`

	// ProactiveHistoryFile is the path (relative to content_dir) where recent
	// proactive message outputs are logged so Claude can avoid repetition.
	// Default: "AutoGenerated/proactive-history.md".
	ProactiveHistoryFile string `json:"proactive_history_file"`

	WriteHistory bool `json:"write_history"`

	// DayBoundaryHour defines the start of a "new day" in local time, 0..23.
	// Used by multiple subsystems (e.g. agent session rotation).
	DayBoundaryHour int `json:"day_boundary_hour"`

	// AgentSessionExtendIfInteractedWithin keeps an agent session alive across
	// the day boundary if there was interaction within this duration.
	AgentSessionExtendIfInteractedWithin time.Duration `json:"agent_session_extend_if_interacted_within"`
}

func DefaultConfig() Config {
	return Config{
		RawInputsDir:                         "RawInputs",
		PromptsDir:                           "Prompts",
		HealthFile:                           "AutoGenerated/health.md",
		ProactiveHistoryFile:                 "AutoGenerated/proactive-history.md",
		DayBoundaryHour:                      5,
		AgentSessionExtendIfInteractedWithin: 1 * time.Hour,
	}
}

var builtinIgnores = []string{
	"AGENTS.md",
	"CLAUDE.md",
	"GEMINI.md",
	"{RawInputs}",
	"{Prompts}",
}

type Secrets struct {
	OpenAIKey        string `json:"OPENAI_API_KEY"`
	TelegramBotToken string `json:"TELEGRAM_BOT_TOKEN"`
	TelegramChatID   string `json:"TELEGRAM_CHAT_ID"`
}

func mustResolvePath(baseDir, p, title string) string {
	p = resolvePath(baseDir, p)
	if p == "" {
		log.Fatalf("lifebase configuration error: %s resolved to empty", title)
	}
	_, err := os.Stat(p)
	if err != nil {
		log.Fatalf("lifebase configuration error: %s does not exist", p)
	}
	return p
}

func resolvePath(baseDir, p string) string {
	p = strings.TrimSpace(p)
	if p == "" {
		return ""
	}
	if filepath.IsAbs(p) {
		return filepath.Clean(p)
	}
	return filepath.Clean(filepath.Join(baseDir, filepath.FromSlash(p)))
}

func promptPath(name string) string {
	name = strings.TrimSpace(name)
	if name == "" {
		return ""
	}
	if filepath.IsAbs(name) {
		return filepath.Clean(name)
	}
	rel := filepath.FromSlash(name)
	return filepath.Join(promptsDir, rel)
}
