package main

import (
	"embed"
	"errors"
	"fmt"
	"io/fs"
	"log"
	"os"
	"path"
	"path/filepath"
	"strings"
	"time"
)

//go:embed example/** example/.gitignore
var exampleTemplates embed.FS

type initStats struct {
	created int
	merged  int
	skipped int
}

func initRepo(configFile string, now time.Time) error {
	configPath := must(filepath.Abs(configFile))
	configName := filepath.Base(configPath)
	if ext := strings.ToLower(filepath.Ext(configName)); ext != ".yaml" && ext != ".yml" {
		return fmt.Errorf("-init requires a YAML config file name, got %q", configName)
	}

	targetRoot := filepath.Dir(configPath)
	if err := os.MkdirAll(targetRoot, 0o777); err != nil {
		return err
	}

	now = now.Local()
	var stats initStats
	if err := fs.WalkDir(exampleTemplates, "example", func(examplePath string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}

		relPath := strings.TrimPrefix(examplePath, "example/")
		if relPath == "" {
			return nil
		}
		targetRelPath := applyInitPlaceholders(relPath, now)
		if relPath == "lifebase.yaml" {
			targetRelPath = configName
		}
		targetPath := filepath.Join(targetRoot, filepath.FromSlash(targetRelPath))

		templateData, err := fs.ReadFile(exampleTemplates, examplePath)
		if err != nil {
			return err
		}
		rendered := applyInitPlaceholders(string(templateData), now)

		if path.Base(relPath) == ".gitignore" {
			changed, err := mergeInitGitignore(targetPath, rendered)
			if err != nil {
				return err
			}
			if changed {
				stats.merged++
			} else {
				stats.skipped++
			}
			return nil
		}

		wrote, err := writeInitFileIfMissing(targetPath, rendered)
		if err != nil {
			return err
		}
		if wrote {
			stats.created++
		} else {
			stats.skipped++
		}
		return nil
	}); err != nil {
		return err
	}

	for _, relDir := range []string{"Raw", "AutoGenerated"} {
		fullDir := filepath.Join(targetRoot, filepath.FromSlash(relDir))
		if err := os.MkdirAll(fullDir, 0o777); err != nil {
			return err
		}
	}

	log.Printf("Initialized lifebase in %s (%d created, %d merged, %d skipped)", targetRoot, stats.created, stats.merged, stats.skipped)
	return nil
}

func applyInitPlaceholders(s string, now time.Time) string {
	replacer := strings.NewReplacer(
		"YYYY-MM-DD", now.Format("2006-01-02"),
		"YYYY-MM", now.Format("2006-01"),
		"YYYY", now.Format("2006"),
		"DDD", now.Format("Mon"),
	)
	return replacer.Replace(s)
}

func writeInitFileIfMissing(targetPath string, content string) (bool, error) {
	if info, err := os.Stat(targetPath); err == nil {
		if info.IsDir() {
			return false, fmt.Errorf("%s exists and is a directory", targetPath)
		}
		return false, nil
	} else if !errors.Is(err, os.ErrNotExist) {
		return false, err
	}

	if err := os.MkdirAll(filepath.Dir(targetPath), 0o777); err != nil {
		return false, err
	}
	if err := os.WriteFile(targetPath, []byte(ensureTrailingNewline(content)), 0o666); err != nil {
		return false, err
	}
	return true, nil
}

func mergeInitGitignore(targetPath string, template string) (bool, error) {
	templateLines := nonEmptyLines(template)
	if len(templateLines) == 0 {
		return false, nil
	}

	existing, err := os.ReadFile(targetPath)
	if errors.Is(err, os.ErrNotExist) {
		if err := os.MkdirAll(filepath.Dir(targetPath), 0o777); err != nil {
			return false, err
		}
		if err := os.WriteFile(targetPath, []byte(ensureTrailingNewline(strings.Join(templateLines, "\n"))), 0o666); err != nil {
			return false, err
		}
		return true, nil
	}
	if err != nil {
		return false, err
	}

	existingLines := nonEmptyLines(string(existing))
	existingSet := make(map[string]struct{}, len(existingLines))
	for _, line := range existingLines {
		existingSet[line] = struct{}{}
	}

	var missing []string
	for _, line := range templateLines {
		if _, ok := existingSet[line]; !ok {
			missing = append(missing, line)
		}
	}
	if len(missing) == 0 {
		return false, nil
	}

	mergedLines := append(existingLines, missing...)
	if err := os.WriteFile(targetPath, []byte(ensureTrailingNewline(strings.Join(mergedLines, "\n"))), 0o666); err != nil {
		return false, err
	}
	return true, nil
}

func nonEmptyLines(s string) []string {
	s = strings.ReplaceAll(s, "\r\n", "\n")
	parts := strings.Split(s, "\n")
	out := parts[:0]
	for _, part := range parts {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		out = append(out, part)
	}
	return out
}

func ensureTrailingNewline(s string) string {
	if strings.HasSuffix(s, "\n") {
		return s
	}
	return s + "\n"
}
